### ISSUE TITLE
crash every time when quitting

### ISSUE THREAD

**Issue by sherocyc** [Koderz/UE4RuntimeMeshComponent#1]
MachineId:FFE9D4CE4D347057434FBAA0D71D517A
EpicAccountId:0a07e675f2fb47b899c2f761b279eac9

Access violation - code c0000005 (first/second chance not available)

PhysX3CommonPROFILE_x64!physx::shdfnd::atomicDecrement() [d:\ori.cohen_g6217_physics\engine\source\thirdparty\physx\physx-3.3\source\foundation\src\windows\pswindowsatomic.cpp:45]
PhysX3PROFILE_x64!physx::NpShape::~NpShape() [d:\ori.cohen_g6217_physics\engine\source\thirdparty\physx\physx-3.3\source\physx\src\npshape.cpp:53]
PhysX3PROFILE_x64!physx::NpShape::`scalar deleting destructor'()
PhysX3PROFILE_x64!physx::NpFactory::releaseShapeToPool() [d:\ori.cohen_g6217_physics\engine\source\thirdparty\physx\physx-3.3\source\physx\src\npfactory.cpp:874]
PhysX3PROFILE_x64!physx::NpDestroy() [d:\ori.cohen_g6217_physics\engine\source\thirdparty\physx\physx-3.3\source\physx\src\npfactory.cpp:1249]
PhysX3PROFILE_x64!physx::Scb::Scene::remove<physx::Scb::Body,1>() [d:\ori.cohen_g6217_physics\engine\source\thirdparty\physx\physx-3.3\source\physx\src\buffering\scbscene.cpp:411]
PhysX3PROFILE_x64!physx::Scb::Scene::removeRigidBody() [d:\ori.cohen_g6217_physics\engine\source\thirdparty\physx\physx-3.3\source\physx\src\buffering\scbscene.cpp:601]
PhysX3PROFILE_x64!physx::NpRigidDynamic::release() [d:\ori.cohen_g6217_physics\engine\source\thirdparty\physx\physx-3.3\source\physx\src\nprigiddynamic.cpp:66]
UE4Editor_Engine!TermBodyHelper() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\engine\private\physicsengine\bodyinstance.cpp:1947]
UE4Editor_Engine!FBodyInstance::TermBody() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\engine\private\physicsengine\bodyinstance.cpp:2000]
UE4Editor_Engine!UPrimitiveComponent::DestroyPhysicsState() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\engine\private\components\primitivecomponent.cpp:616]
UE4Editor_Engine!UActorComponent::ExecuteUnregisterEvents() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\engine\private\components\actorcomponent.cpp:1120]
UE4Editor_Engine!UActorComponent::UnregisterComponent() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\engine\private\components\actorcomponent.cpp:945]
UE4Editor_Engine!AActor::UnregisterAllComponents() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\engine\private\actor.cpp:3861]
UE4Editor_Engine!ULevel::ClearLevelComponents() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\engine\private\level.cpp:686]
UE4Editor_Engine!UWorld::ClearWorldComponents() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\engine\private\world.cpp:1307]
UE4Editor_Engine!UWorld::CleanupWorld() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\engine\private\world.cpp:3288]
UE4Editor_UnrealEd!UEditorEngine::TeardownPlaySession() [d:\build\++ue4+release-4.12+compile\sync\engine\source\editor\unrealed\private\playlevel.cpp:653]
UE4Editor_UnrealEd!UEditorEngine::EndPlayMap() [d:\build\++ue4+release-4.12+compile\sync\engine\source\editor\unrealed\private\playlevel.cpp:255]
UE4Editor_UnrealEd!UEditorEngine::Tick() [d:\build\++ue4+release-4.12+compile\sync\engine\source\editor\unrealed\private\editorengine.cpp:1399]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [d:\build\++ue4+release-4.12+compile\sync\engine\source\editor\unrealed\private\unrealedengine.cpp:368]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\launch\private\launchengineloop.cpp:2775]
UE4Editor!GuardedMain() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\launch\private\launch.cpp:148]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [d:\build\++ue4+release-4.12+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:200]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264]
kernel32
ntdll

**Comment by sherocyc** [comment]
ProceduralMeshComponent won't cause the issue

**Comment by Koderz** [comment]
@sherocyc Would you be willing to share how you're setting up collision with the RMC? Also, are you using the github branch or one of the releases?

**Comment by sherocyc** [comment]
I'm making something like Minecraft.The collision is generated by CreateMeshSection(index,positions,triangles,normals,uvs,colors,tangens,collision),the last param true.I'm using the github version.
Sorry about my English ,I hope you can understand :)

**Comment by Koderz** [comment]
@sherocyc  Sorry about not getting back to you, been swamped in classwork for the past 2 weeks. 

I can't reproduce that issue locally. Are you able to reproduce it in a new project?

**Comment by Koderz** [comment]
Haven't heard from you in a while, and cannot reproduce this issue so will be closing it. If you still have problems, feel free to reopen the issue.
