### ISSUE TITLE
Vertex operator< inconsitent

### ISSUE THREAD

**Issue by sackyhack** [Koderz/UE4RuntimeMeshComponent#10]
The current implementation of operator< in the Vertex struct would have (3,4,5) < (5,4,3), but it would also have (5,4,3) < (3,4,5)

**Comment by Koderz** [comment]
Hey, not quite sure which vertex you're referring too.  The template vertex doesn't have that operator IIRC.

**Comment by sackyhack** [comment]
Sorry about that.  I'm not really sure this is a problem in practice.  I am referring to the Vertex struct declared in TessellationUtilities.h

**Comment by Koderz** [comment]
Ah yeah, that's a logic port of the nvidia tessellation utilities so I assumed they set it up like that for a reason. It appears to work correctly so  I'll leave it as it is for now.

**Comment by sackyhack** [comment]
OK.  Thanks for looking.
