### ISSUE TITLE
Help wanted: Curious on best approach to update normals

### ISSUE THREAD

**Issue by allybarrow** [Koderz/UE4RuntimeMeshComponent#11]
Hi, sorry, bad form to leave a help request as an issue like this: just a quick question if you don't mind?

Currently building a DualBuffer mesh with positions, DualUV vertex data and the EUpdateFrequency::Frequent flag set.

Then updating in the loop with BeginMeshSectionPositionUpdate for speed.

This works fine, though very quickly the normal info is completely wrong.

Question is, what is the most efficient way to update the Normals? It seems to update normals I would call CalculateTangentsForMesh then revert to UpdateMeshSection which seems a backwards step from the efficient BeginMeshSectionPositionUpdate approach?

Thanks!
Ally

**Comment by Koderz** [comment]
Unfortunately, it's not super well setup for that yet. One of the things I'm working on is to rearrange the dual buffered sections to allow for customizing what is in each, so for example buffer 1 could be pos/norm/tan,   and buffer 2 could be color/uv0/uv1    or something like that.   It's something I want to add here soon after the other currently in progress stuff is done, but I have no guarantee when that will be.   It was kind of a hack to support position only both as a test and to support a specific use case of mine.

Now, If you're going to be updating all of that, then the best thing is probably not to use dual buffered sections and instead use the same config for fast update, but just a single buffer as gpu lock time will play into this as well.

I can tell you that for any non-trivial sized mesh "CalculateTangentsForMesh" is going to be by far the most expensive part of that.  There's some stuff I have planned for that function specifically but I honestly don't expect to do that for a while.
