### ISSUE TITLE
Noob question about packed vertex arrays.

### ISSUE THREAD

**Issue by SillyMind69** [Koderz/UE4RuntimeMeshComponent#13]
Hello! If I use packed vertex structures for example:

Vertices.Add(FRuntimeMeshVertexSimple(FVector(0, 100, 0), FVector(0, 0, 1), FRuntimeMeshTangent(0, -1, 0), FColor::White, FVector2D(0, 0)));

Vertices.Add(FRuntimeMeshVertexSimple(FVector(0, 100, 0), FVector(0, 0, 1), FRuntimeMeshTangent(0, -1, 0), FColor::White, FVector2D(0, 0)));

How can I access  Vertex Coordinates of each Vertices Array?

**Comment by Koderz** [comment]
Not quite sure what you mean.  If you mean accessing the components of the vertices in the array you just made...

Vertices[VertexIndex].Position = FVector(0,0,0);

type of thing...  Not sure if that's what you meant though.
