### ISSUE TITLE
Need support for PT_4_ControlPointPatchList

### ISSUE THREAD

**Issue by greenmughal** [Koderz/UE4RuntimeMeshComponent#14]
Hi, 
I have successfully made (WIP) planet rendering in OpenGL/DX but im new to unreal 4 and could find a base to start with, can you kindly add support for PT_4_ControlPointPatchList with tessellation shader support, because a quad is better looking when tessellated than triangles for planet.

Or atleast guide me the places where and what needs to change to support  PT_4_ControlPointPatchList!

**Comment by Koderz** [comment]
Adding support for setting the vbo type is doable, but to my knowledge this wouldn't work with the material system. You'd have to do completely custom shaders. Internally UE4 only really uses one structure of tessellation information since it really just has 2 variants of the same thing.

**Comment by Koderz** [comment]
Haven't heard from you in a while, so I'm closing this issue. Feel free to reopen it if you need further assistance.
