### ISSUE TITLE
SMC -> RMC Conversion

### ISSUE THREAD

**Issue by korcanergun** [Koderz/UE4RuntimeMeshComponent#16]
Hi,

I am trying to convert SMC to RMC at runtime. But im getting memory errors. I am using UE 4.14 .

mainStaticMesh is UStaticMeshComponent and filled with my static mesh.

`URuntimeMeshLibrary::CopyRuntimeMeshFromStaticMeshComponent(mainStaticMesh, 0, RuntimeMesh, false);`

Best,

**Comment by Koderz** [comment]
Hello @korcanergun   What errors are you getting?  Nothing appears out of the ordinary there.

**Comment by Koderz** [comment]
Haven't heard from you in a while. I'm closing this issue but if you are still experiencing this error feel free to reopen it.
