### ISSUE TITLE
BeginMeshSectionPositionUpdate returns NULL?

### ISSUE THREAD

**Issue by Zinglish** [Koderz/UE4RuntimeMeshComponent#17]
Hey Koderz, I'm having an issue with BeginMeshSectionPositionUpdate: `TArray<FVector>& Vertices = *CSGMesh->RMC->BeginMeshSectionPositionUpdate(0);` and `Vertices` is NULL.

The code that creates the vertices is below:

```
TArray<FVector> Positions;
TArray<FRuntimeMeshVertexNoPosition> VertexData;

FBox BoundingBox = FBox(FVector(1000.f, 1000.f, 1000.f), FVector(-1000.f, -1000.f, -1000.f));
	
URuntimeMeshLibrary::CreateBoxMesh(FVector(Size, Size, Size), Positions, Triangles, Normals, TextureCoordinates, Tangents);

for(int32 i = 0; i < Normals.Num(); i++)
	VertexData.Add(FRuntimeMeshVertexNoPosition(Normals[i], Tangents[i], TextureCoordinates[i]));

RMC->CreateMeshSectionDualBuffer(0, Positions, VertexData, Triangles, BoundingBox, false, EUpdateFrequency::Frequent);
```

I would like to create a cube that I can then move the faces/create new ones during a runtime level editor I am working on.

**Comment by Zinglish** [comment]
Nevermind, silly UE4 messing me around again.

**Comment by Koderz** [comment]
Well glad it worked! Was about to say none of my tests showed anything wrong.

**Comment by Zinglish** [comment]
The problem was (for people who come across this too) that UE4 somehow serialized the class I had placed in the editor; I had originally coded the mesh to generate using `CreateMeshSection()`, placed the mesh in the editor then modified the code to generate using `CreateMeshSectionDualBuffer()` which caused `BeginMeshSectionPositionUpdate()` to return NULL. All I needed to do was delete the class I added to the editor scene and re-add it again and it all worked.

Thanks for the quick reply btw! RMC is fantastic and I love it! Please keep up the awesome work!

**Comment by Koderz** [comment]
Yeah, the editor can get kinda strange with things like this...Usually retriggering the construction (by moving in editor or recompiling the BP) is enough to fix things like that.

Glad to hear it was useful! Got big things in store for v3!
