### ISSUE TITLE
BodySetup access

### ISSUE THREAD

**Issue by armabon** [Koderz/UE4RuntimeMeshComponent#18]
Hi, 
In the PMC, a function GetBodySetup allow us to access to the bodySetup of a PMC . I saw that in the RMC you made the bodySetup directly accessible via a pointer but it is always empty for me(Not containing any convex).

Best,

**Comment by Koderz** [comment]
Well the convex objects aren't handled there currently, and instead is handled currently more like the PMC. With that the body setup only has them after it's cooked. What are you trying to do with them though?

**Comment by armabon** [comment]
Hi,
I am trying to duplicate the RMC.

**Comment by Koderz** [comment]
Ah… yeah… Well the best solution is to query the convex elements directly and copy those.  I believe It’s just RMC->ConvexCollisionSections.

Unfortunately what you’re doing will require multiple full copies of the mesh data on both main ram and vram + multiple mesh copies in PhysX… So I’d be careful on the quantity. With that said this is one of the driving reasons for the complete rewrite I’m currently doing so “Instancing” will be directly supported in the next version hopefully.

**Comment by armabon** [comment]
Thank you :)
