### ISSUE TITLE
Crash opening editor without rebuild - Trying to recreate class 'URuntimeMeshComponent' outside of hot reload!

### ISSUE THREAD

**Issue by abecks** [Koderz/UE4RuntimeMeshComponent#20]
I have to rebuild my project in Visual Studio before I can open the editor. I just added RMC to an actor in the scene. After rebuilding, the editor will open and won't crash again until I try to reopen it later on.

```
Assertion failed: GIsHotReload [File:D:\Build\++UE4+Release-4.13+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectBase.cpp] [Line: 579] 
Trying to recreate class 'URuntimeMeshComponent' outside of hot reload!


UE4Editor_CoreUObject!CreatePackage() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:543]
UE4Editor_CoreUObject!UObjectLoadAllCompiledInStructs() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\coreuobject\private\uobject\uobjectbase.cpp:781]
UE4Editor_CoreUObject!ProcessNewlyLoadedUObjects() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\coreuobject\private\uobject\uobjectbase.cpp:829]
UE4Editor_CoreUObject!TBaseStaticDelegateInstance<void __cdecl(void)>::ExecuteIfSafe() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:1017]
UE4Editor_Core!TBaseMulticastDelegate<void>::Broadcast() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:921]
UE4Editor_Core!FModuleManager::LoadModuleWithFailureReason() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\core\private\modules\modulemanager.cpp:424]
UE4Editor_Projects!FModuleDescriptor::LoadModulesForPhase() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\projects\private\moduledescriptor.cpp:398]
UE4Editor_Projects!FPluginManager::LoadModulesForEnabledPlugins() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\projects\private\pluginmanager.cpp:559]
UE4Editor!FEngineLoop::LoadStartupModules() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\launch\private\launchengineloop.cpp:2218]
UE4Editor!FEngineLoop::PreInit() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\launch\private\launchengineloop.cpp:1653]
UE4Editor!GuardedMain() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\launch\private\launch.cpp:117]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [d:\build\++ue4+release-4.13+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:202]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264]
kernel32
ntdll
```

Any idea what would be causing this?

**Comment by Koderz** [comment]
Haven't seen that before... Not sure what would cause that.

Is it reproducible outside of your project, like in a basic project?

**Comment by abecks** [comment]
I'll give that a shot, although I have a very small project right now. Maybe I could share it with you?

**Comment by Koderz** [comment]
Yeah, if you're willing to do that feel free! Feel free to contact me directly either through the UE4 Discord or my email chris@koderz.me

**Comment by abecks** [comment]
Thanks for taking a look. I've uploaded it to Google Drive here:
https://drive.google.com/open?id=0Bw79xAK-G5jhM0NoWU51alNoajA

This is my first C++ and UE4 project so there's a good chance it's
something I'm doing wrong, but I can't seem to tell what it is. Spent a few
days searching on the forums and trying different things without success.

The scene is pretty simple, there is a VoxelWorld actor that spawns several
VoxelChunk actors. The chunks use RMC to render a cube based mesh.

The problem happens when I build normally from Visual Studio or the compile
button, then close UE4 and open it again later. The error occurs while it
is loading the editor. I have to load Visual Studio, do a full rebuild, and
then I can work with it again. It works fine as long as the editor is left
open.

I really appreciate the help!

**Comment by abecks** [comment]
Fixed!

I switched to the marketplace version of RMC and the error has gone away. I believe it was either because I was using a checkout from the master branch here, or that I was using the RMC with slicer support before. I suspect it has something to do with the plugin system, since I had it manually added as a plugin in my projects Plugins directory.

The error occurred after doing a hot reload, then closing and re-opening the editor. Only a rebuild from VS would allow me to launch the editor.

**Comment by adarshmuthappa** [comment]
I face the same issue everytime I open my project which has this plugin enabled. I am forced to rebuild from VS to open the editor. I am **not** using the marketplace version of this plugin.

**Comment by dc5ala** [comment]
I can report the same issue here with 4.17.1 and a manually installed current checkout of RMC (2.1?). I have to rebuild in VS to start the editor. Every time I try packaging I get this error.

UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: === Critical error: ===
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: 
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: Assertion failed: GIsHotReload [File:D:\Build\++UE4+Release-4.17+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectBase.cpp] [Line: 608] 
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: Trying to recreate class 'URuntimeMeshComponent' outside of hot reload!
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: 
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: 
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffff
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: 
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-CoreUObject.dll!0x00000000BE1928E9
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-CoreUObject.dll!0x00000000BE1D3816
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-CoreUObject.dll!0x00000000BE01C497
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-Cmd.exe!0x000000000832F915
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-Cmd.exe!0x000000000832F783
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-Cmd.exe!0x0000000008332DE1
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-Cmd.exe!0x00000000083339A5
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-Cmd.exe!0x00000000083339EA
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-Cmd.exe!0x00000000083402D9
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: UE4Editor-Cmd.exe!0x0000000008341083
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: KERNEL32.DLL!0x00000000DF472774
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: ntdll.dll!0x00000000E1A60D51
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: ntdll.dll!0x00000000E1A60D51
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: 
UATHelper: Packaging (Windows (64-bit)): Cook: LogWindows: Error: end: stack for UAT
