### ISSUE TITLE
Use proceedural mesh as collision mesh without baking?

### ISSUE THREAD

**Issue by abecks** [Koderz/UE4RuntimeMeshComponent#24]
Is it possible to use the generated mesh as the collision mesh without baking? I tried to set `bUseComplexAsSimple` to true but I still needed to have the RMC bake the collision mesh. Can it be set similar to convex collision?

**Comment by Koderz** [comment]
Sorry about the late response..

Unfortunately whether you use complex or simple, PhysX will have to cook it. The purpose behind that is to generate a culling structure (among others) that without that you'd have to brute force detect things which can get horridly slow. two 100 tri meshes would be 10,000 possible collisions without some way to quickly cull them like what the BVH PhysX uses internally does.
