### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by unktomi-g** [Koderz/UE4RuntimeMeshComponent#25]
Hello, I'm getting the following error at runtime (built for Android_ASTC):
Fatal error: [File:D:\Github\unktomi-g\UnrealEngine\Engine\Source\Runtime\Engine\Private\PhysicsEngine\BodySetup.cpp] [Line: 804]
LogPlayLevel: adb:
LogPlayLevel: adb: 02-04 03:56:11.449 26963 26988 D UE4     : This platform requires cooked packages, and physX data was not cooked into BodySetup /Game/chrisContent/Scenes/Dreamworld.Dreamworld:PersistentLevel.OasisMeshBuilder_C_0.RuntimeMesh.BodySetup_2.

Any insight is much appreciated :)

In my case, I don't need collision for the runtime mesh and tried turning it off but I get the same result.

**Comment by unktomi-g** [comment]
I can add that this occurs only when I spawn the actor that contains the runtime mesh component. If statically place the actor in a level everything works as expected.

**Comment by Koderz** [comment]
Sorry about the late response...

Android doesn't support runtime collision cooking by default. You can enable it, but it would require building the engine from source to do it unfortunately. This is a decision by Epic as cooking is a pretty heavy operation.

**Comment by Koderz** [comment]
I haven't heard from you in a while so I'm going to go ahead and close this. If this is still an issue, feel free to reopen it.
