### ISSUE TITLE
Can't use SplineComponent.h (and most other headers) in a project which uses the RMC

### ISSUE THREAD

**Issue by Zireael07** [Koderz/UE4RuntimeMeshComponent#26]
VS spits out a ton of errors upon trying to compile when having `#include Components/SplineComponent.h` :

https://hastebin.com/vavaqebogu.tex

**Comment by Zireael07** [comment]
@Koderz

**Comment by Koderz** [comment]
I haven't been able to reproduce this locally. What engine version are you using?

**Comment by Zireael07** [comment]
4.14.0, Windows 64-bit, no other plugins

**Comment by Koderz** [comment]
I still can't recreate that.   What other includes do you have and what is the folder structure of your project?

**Comment by Zireael07** [comment]
I have split the cpp and headers into /Public and /Private folders, maybe that is a factor?

Otherwise, no other includes.

**Comment by Koderz** [comment]
That shouldn't affect anything. The only time I've seen something like that happen (wasn't with the RMC) but it's if you mimic a folder within UE4. so for example if you have a Core folder which the engine has its own I've seen UBT trip up on some things in that case but that was over a year ago.  Not really sure why you're gettin that as none of my attempts to recreate it have failed to compile

**Comment by Koderz** [comment]
I haven't heard from you in a while so I'm going to go ahead and close this. If this is still an issue, feel free to reopen it.
