### ISSUE TITLE
Get mesh data

### ISSUE THREAD

**Issue by adarshmuthappa** [Koderz/UE4RuntimeMeshComponent#29]
How would I go about getting the mesh data like vertices, triangles, UVs and normals from a runtime mesh?

GetSectionMesh() gives me vertices and indices. How do I get UVs, normals, tangents and Vertex Colors?

**Comment by Zinglish** [comment]
Well if you built the mesh section manually you should definitely already know the tris, vertices, normals, UVs and vertex colors. If you created the section from one of the procedural methods of RMC then the outputs of the relevant parameters will tell you exactly what you want:

```
TArray<FVector>             Vertices;
TArray<FVector>             Normals;
TArray<FRuntimeMeshTangent> Tangents;
TArray<FVector2D>           TextureCoords;
TArray<int32>               Triangles;

URuntimeMeshLibrary::CreateBoxMesh(FVector(Size, Size, Size), Vertices, Triangles, Normals, TextureCoordinates, Tangents);
```

Also: knowing just the vertices and the indices you can get tris, normals, etc. Here's an accurate example of how to calculate the normals of a triangle index:

```
FVector CalculateTriangleNormal(int32 TriangleIndex)
{
	int32 VertOffset = TriangleIndex * 3;

	FVector Cross = FVector::CrossProduct(
		Vertices[Triangles[VertOffset + 2]] - Vertices[Triangles[VertOffset + 0]],  // Edge 1
		Vertices[Triangles[VertOffset + 1]] - Vertices[Triangles[VertOffset + 0]]); // Edge 2
	Cross.Normalize();

	return Cross;
}
```

I think you need to read this Wiki entry: [Mesh Basics](https://github.com/Koderz/UE4RuntimeMeshComponent/wiki/Mesh-Basics). I also recommend doing more research on 3D geometry to better understand how just knowing the vertex positions and windings can get you triangles, the normals of those triangles, tangents, etc.

**Comment by adarshmuthappa** [comment]
Fair enough, thanks for the info @Zinglish 

How would I get the Vertex Buffer info for a mesh? Although I created the mesh I dont want to hold all these values as I assume the RuntimeMeshComponent would. I just need a way to access the Vertex buffer whenever I need. Is it exposed?

**Comment by Zinglish** [comment]
Again, you should do some more research and reading before opening an issue to talk about information that's readily available. There's [examples](https://github.com/Koderz/UE4RuntimeMeshComponentExamples) on how to use RMC, in the [Animated Terrain Demo](https://github.com/Koderz/UE4RuntimeMeshComponentExamples/blob/master/Source/RMC_Examples/Actors/AnimatedTerrain.cpp) you can see how to grab and use the vertex buffer. Regardless I will, for the sake of anyone who's stuck on, this provide a minimal approach below.

If you create a mesh doing something like
```
TArray<FRuntimeMeshVertexNoPosition> VertexData;

FBox BoundingBox = FBox(FVector(Size, Size, Size), FVector(-Size, -Size, -Size));

URuntimeMeshLibrary::CreateBoxMesh(FVector(Size, Size, Size), Vertices, Triangles, Normals, TextureCoordinates, Tangents);

for(int32 i = 0; i < Normals.Num(); i++)
		VertexData.Add(FRuntimeMeshVertexNoPosition(Normals[i], Tangents[i], TextureCoordinates[i]));

RMC->CreateMeshSectionDualBuffer(0, Vertices, VertexData, Triangles, BoundingBox, true, EUpdateFrequency::Frequent);
```

You can later get the vertex buffer with the following method
```
TArray<FVector>& Vertices = *RMC->BeginMeshSectionPositionUpdate(0);
```

You would then modify and vertices in the `Vertices` array then call `RMC->EndMeshSectionPositionUpdate(0);` which will force RMC to update the vertices in the UE4 renderer.

Do note that adding or removing any verts from the array returned from `BeginMeshSectionPositionUpdate()` will likely result in a crash or unexpected behaviour. If you wish to add or remove verts from your mesh, I believe you will need to rebuild it entirely, discarding all other information about the mesh, I haven't experimented with this myself all that much tbh.

**Comment by adarshmuthappa** [comment]
I have no intention of updating an exisiting mesh so I really don't think using `BeginMeshSectionPositionUpdate(0)` is correct. It doesn't seem like it was meant to just get a reference. 

Anyway, this worked for me - 

```	
const IRuntimeMeshVerticesBuilder* runtimeVertices;
const FRuntimeMeshIndicesBuilder* runtimeIndices;
Mesh->GetSectionMesh(0, runtimeVertices, runtimeIndices);
```

Thanks for your help @Zinglish.
