### ISSUE TITLE
RuntimeMeshGenericVertex.h Declaration Order

### ISSUE THREAD

**Issue by 11011001** [Koderz/UE4RuntimeMeshComponent#3]
It is not possible to build RMC on OS X with the declaration order in RuntimeMeshGenericVertex.h. Clang is pretty picky about the declaration order inside source files, if a struct depends on another struct, the dependency has to be declared first.

I'd submit a patch, but I gave up after running into C++14 build errors (unsupported by unreal on OS X).

**Comment by 11011001** [comment]
Pull request created: https://github.com/Koderz/UE4RuntimeMeshComponent/pull/4

**Comment by Koderz** [comment]
I think this is mostly resolved at this point. Let me know if there's anything more with the new version!
