### ISSUE TITLE
Can I only change vertex‘s color without cooking coliision

### ISSUE THREAD

**Issue by zfyu222** [Koderz/UE4RuntimeMeshComponent#32]
I am using this plugin in my project，and  Often need to update the vertex color without other data.Now I have to recreate MeshSection(Or updateMeshSection) ，Which can lead to unnecessary performance overhead with physice recook,but I did not actually change the mesh shape.Can I only change vertex‘s color without cooking coliision.

**Comment by indyfree** [comment]
@zfyu222 How do you display the vertex colors in the engine? 
Just setting the Vertex colors like this:
`RuntimeMesh->CreateMeshSection(0, Vertices, Triangles, Normals, TextureCoordinates, VertexColors, Tangents);` does not do the trick for me. 
The mesh keeps showing with the standard texture. Do I need to create a texture from the vertex colors?

**Comment by Koderz** [comment]
Well.. honestly no you can't really change it directly without recooking the collision... That's something I'll keep in mind for the new version.  

The way you can get around this is use the separate collision. CreateMeshCollisionSection() or something like that, I don't remember the exact name. You could use that to handle the collision and then just disable collision on the normal section you want to change frequently.

**Comment by zfyu222** [comment]
Thank you reply.Separating collision and rendering  is indeed a feasible solution
