### ISSUE TITLE
No gravity with RMC?

### ISSUE THREAD

**Issue by DarkestVoid** [Koderz/UE4RuntimeMeshComponent#36]
The RMC doesn't seem to be affected by physics. I turned on 'Simulate Physics' and 'Enable Gravity' for the RMC but with no effect.
I tried with the example project (https://github.com/Koderz/UE4RuntimeMeshComponentExamples) with UE Version 4.14.3 and in my own project with version 4.15.0
Is it somehow possible to have a RMC that is affected by gravity?
If not is it possible to save the mesh of the RMC using C++? (I have seen that this is possible in the editor)

**Comment by BitingBum** [comment]
For RMC 3.0 i use Set Mobility
