### ISSUE TITLE
'TypeInfo': is not a member of FVector

### ISSUE THREAD

**Issue by hclmed** [Koderz/UE4RuntimeMeshComponent#40]
I'm calling

`DisparityMesh->CreateMeshSection(0, vertices, Triangles, false);`

Where vertices is `TArray<FVector>` and Triangles is `TArray<int32>`

When compiling, I get this problem

    d:\ue4_dev\nvidia_ue4_14\engine\plugins\runtimemeshcomponent\source\runtimemeshcomponent\public\RuntimeMeshSection.h(542): note: while compiling class template member function 'const FRuntimeMeshVertexTypeInfo *FRuntimeMeshSection<VertexType>::GetVertexType(void) const'
    2>          with
    2>          [
    2>              VertexType=FVector
    2>          ]
    2>  d:\ue4_dev\nvidia_ue4_14\engine\source\runtime\core\public\templates\PointerIsConvertibleFromTo.h(16): note: see reference to class template instantiation 'FRuntimeMeshSection<VertexType>' being compiled
    2>          with
    2>          [
    2>              VertexType=FVector
    2>          ]
    2>  D:\UE4_Dev\NVIDIA_UE4_14\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h(518): note: see reference to class template instantiation 'TPointerIsConvertibleFromTo<ObjectType,const UObjectBase>' being compiled
    2>          with
    2>          [
    2>              ObjectType=FRuntimeMeshSection<FVector>
    2>          ]
    2>  D:\UE4_Dev\NVIDIA_UE4_14\Engine\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Public\RuntimeMeshComponent.h(171): note: see reference to class template instantiation 'TSharedPtr<FRuntimeMeshSection<VertexType>,0>' being compiled
    2>          with
    2>          [
    2>              VertexType=FVector
    2>          ]
    2>  D:\_User\Username\Documents\Unreal Projects\OpenCVCollisionTest2\Source\OpenCVCollisionTest\CVStereoReader.cpp(247): note: see reference to function template instantiation 'void URuntimeMeshComponent::CreateMeshSection<FVector>(int32,TArray<FVector,FDefaultAllocator> &,TArray<ElementType,FDefaultAllocator> &,bool,EUpdateFrequency,ESectionUpdateFlags)' being compiled
    2>          with
    2>          [
    2>              ElementType=int32
    2>          ]
    2>d:\ue4_dev\nvidia_ue4_14\engine\plugins\runtimemeshcomponent\source\runtimemeshcomponent\public\RuntimeMeshSection.h(542): error C2065: 'TypeInfo': undeclared identifier

similar to issue #37 

I've built the plugin as an engine plugin on NVIDIA's FLeX 4.14.3 branch: https://github.com/NvPhysX/UnrealEngine/tree/FleX-4.14.3

**Comment by Zinglish** [comment]
Try
```
TArray<FVector>             Vertices;
TArray<FVector>             Normals;
TArray<int32>               Triangles;
TArray<FVector2D>           TextureCoords;
TArray<FColor>              VertexColors;
TArray<FRuntimeMeshTangent> Tangents;

RuntimeMeshComponent->CreateMeshSection(MeshSection, Vertices, Triangles, Normals, TextureCoords, VertexColors, Tangents, true, EUpdateFrequency::Infrequent);
```

The method you're calling won't work with just verts and tris I believe.

**Comment by hclmed** [comment]
Using that version of the method worked. Intellisense pointed me to a templated version of it that only had those parameters. Thank you.
