### ISSUE TITLE
Mesh not created if first vertex is at origin (0,0,0)

### ISSUE THREAD

**Issue by MrIcare14** [Koderz/UE4RuntimeMeshComponent#7]
Hello, 

I'm using the RuntimeMeshComponent from a C++ class using UE4.13.1. I noticed (After hours of research) that (at least for me) if the first vertex passed to the CreateMeshSection is positioned at the origin (0,0,0) or close (<100, <100, <100), the mesh is not created (at least not visible). I discovered RuntimeMeshComponent because ProceduralMeshComponent was not working for, very likely, the same reason. Also from blueprint having the first vertex at origin makes no problem.

I'm fairly new to UE4 so the problem might be entirely my fault.

I add at the end of the message the portion of code generating the problem for me. The commented is copy pasted from the wiki and works. The uncommented one is not.

I hope this is useful and not just a problem I'm the only one to meet.

Regards, 

Code:
mesh = CreateDefaultSubobject<URuntimeMeshComponent>(TEXT("GeneratedMesh"));
	
	TArray<FVector> vertices;
	// First Vertex
	vertices.Add(FVector(0, 0, 0)); // This makes it not working
	//vertices.Add(FVector(50, 50, 0)); // This makes it not working
	//vertices.Add(FVector(100, 100, 0)); // This works

	// Second Vertex
	vertices.Add(FVector(100, 0, 0));

	// Third Vertex
	vertices.Add(FVector(0, 100, 0));

	TArray<int32> triangles;
	triangles.Add(0);
	triangles.Add(1);
	triangles.Add(2);
	
	//triangles.Add(0);
	//triangles.Add(3);
	//triangles.Add(2);

	TArray<FVector> normals;
	normals.Add(FVector(0, 0, 1));
	normals.Add(FVector(0, 0, 1));
	normals.Add(FVector(0, 0, 1));
	//normals.Add(FVector(0, 0, 1));

	TArray<FVector2D> UV;
	UV.Add(FVector2D(0, 0));
	UV.Add(FVector2D(1, 0));
	//UV.Add(FVector2D(1, 1));
	UV.Add(FVector2D(0, 1));

	mesh->CreateMeshSection(0, vertices, triangles, normals, UV, TArray<FColor>(), TArray<FRuntimeMeshTangent>(), false);
	
	
	/*
	// First vertex
	TArray<FVector> Vertices;
	Vertices.Add(FVector(0, 100, 0));
	Vertices.Add(FVector(100, 100, 0));
	Vertices.Add(FVector(100, 0, 0));
	//Vertices.Add(FVector(0, 0, 0));

	TArray<FVector> Normals;
	Normals.Add(FVector(0, 0, 1));
	Normals.Add(FVector(0, 0, 1));
	Normals.Add(FVector(0, 0, 1));
	//Normals.Add(FVector(0, 0, 1));

	TArray<FRuntimeMeshTangent> Tangents;
	Tangents.Add(FRuntimeMeshTangent(0, -1, 0));
	Tangents.Add(FRuntimeMeshTangent(0, -1, 0));
	Tangents.Add(FRuntimeMeshTangent(0, -1, 0));
	Tangents.Add(FRuntimeMeshTangent(0, -1, 0));

	TArray<FVector2D> UV;
	UV.Add(FVector2D(0, 0));
	UV.Add(FVector2D(1, 0));
	//UV.Add(FVector2D(1, 1));
	UV.Add(FVector2D(0, 1));

	TArray<int32> Triangles;
	Triangles.Add(0);
	Triangles.Add(1);
	Triangles.Add(2);

	Triangles.Add(0);
	Triangles.Add(2);
	Triangles.Add(3);

	mesh->CreateMeshSection(0, Vertices, Triangles, Normals, UV, TArray<FColor>(), TArray<FRuntimeMeshTangent>(), false);
	*/

	mesh->SetMeshSectionVisible(0, true);
	RootComponent = mesh;

**Comment by Sergey95ZH** [comment]
First: your initialization of RMC must be like this
`mesh = CreateDefaultSubobject<URuntimeMeshComponent>(TEXT("GeneratedMesh"));`
instead of what you have:
`mesh = CreateDefaultSubobject(TEXT("GeneratedMesh"));`

Have a look at RuntimeMeshComponent [wiki](https://github.com/Koderz/UE4RuntimeMeshComponent/wiki/Working-with-sections-using-component-arrays)

**Comment by Koderz** [comment]
I've not seen any problem like this in any of my tests. It appears to me that the vertex winding order got reversed on your first example and so backface cull kicked in and kept it from rendering. 

I'm gonna go ahead and close this as I haven't heard anything else from you in a while. If you still see this or any other issue feel free to reopen or post a new issue!

Thanks!
