### ISSUE TITLE
UE 4.13 compile error

### ISSUE THREAD

**Issue by goopymoon** [Koderz/UE4RuntimeMeshComponent#8]
Hi Koderz,

Build succeeds in UE 4.12 but fails in UE 4.13. 
It looks like UPOERTY and UENUM cannot be used inside preprocessor in the latest version.

Severity	Code	Description	Project	File	Line	Suppression State
Error		UPROPERTY inside this preprocessor block will be skipped	iBlock	C:\Users\burp\Documents\GitLab\work_iblock\iBlock\Plugins\RuntimeMeshComponent\Source\Public\RuntimeMeshComponent.h	1133	

Severity	Code	Description	Project	File	Line	Suppression State
Error		UENUM inside this preprocessor block will be skipped	iBlock	C:\Users\burp\Documents\GitLab\work_iblock\iBlock\Plugins\RuntimeMeshComponent\Source\Public\RuntimeMeshCore.h	125

**Comment by Koderz** [comment]
Hey @goopymoon 

What version of the RMC are you using? I don't see that problem with 4.13, but I remember that happening on an earlier version.

**Comment by Koderz** [comment]
I haven't heard from you in a while, and I'm unable to reproduce this so I'm closing this. If this continues to be a problem feel free to reopen it.
