### ISSUE TITLE
Spurious vertices created in CopyRuntimeMeshFromStaticMeshComponent

### ISSUE THREAD

**Issue by allybarrow** [Koderz/UE4RuntimeMeshComponent#9]
Hi, firstly this contribution is amazing - thank you!

I'm using CopyRuntimeMeshFromStaticMeshComponent to generate a dynamic mesh from a static one. However, this results in a vertex buffer with lots of additional vertices with random, non-initialized values.

It typically results a bounding box range check throwing an error.

The culprit seems to be the use of the AdjacencyTriangles buffer in GetSectionFromStaticMesh. As it doesn't seem to be used, for now I've just set AdjacencyTriangles to nullptr and moved the AdjacencyTriangles->Reset() call to after the (AdjacencyTriangles != nullptr) check. All seems to work.

Hope that makes sense, interested to know if this is my particular use case or not.

Not sure which commit I'm on, pulled down the master branch today 20/10/2016

Thanks!

**Comment by Koderz** [comment]
Think I found it, stupid mistake. I was reading Indices instead of AdjacencyIndices so it was apparently letting me read out of bounds. Just pushed a fix for it, let me know if you have any more problems

**Comment by allybarrow** [comment]
Ace! Thanks for the fast response, I was pulled onto other projects so only just picking this back up.

Cheers!
